version: 2

jobs:
  "build-rails":
    working_directory: ~/rusperiode/ruslingdk
    docker:
      - image: circleci/ruby:2.5.1-node
      - image: circleci/postgres:9.4.12-alpine

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: ruslingdk-bundler-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: ruslingdk-bundler-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Run rspec in parallel
      - run: |
          bundle exec rails test

  "build-knoldbold":
    docker:
      - image: circleci/openjdk:8u121-jdk

    steps:
      - checkout
      - restore_cache:
          key: tjanser-java-spring-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: tjanser-java-spring-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-rails
      - build-knoldbold